install:
# What is it with CMake and not detecting the right versions of libraries...
- del C:\OpenSSL-Win32\lib\ssleay32.lib
- del C:\OpenSSL-Win32\lib\libeay32.lib
- set BOOST_ROOT=C:\Libraries\boost_1_62_0
- set BOOST_LIBRARYDIR=%BOOST_ROOT%\lib32-msvc-14.0
# Various dependencies needed by Astron...
- cd dependencies
# build yaml-cpp
- appveyor DownloadFile https://github.com/jbeder/yaml-cpp/archive/yaml-cpp-0.6.2.zip -FileName yaml-cpp.zip
- 7z x yaml-cpp.zip
- ren yaml-cpp-yaml-cpp-0.6.2 yaml-cpp
- cd yaml-cpp
- cmake -G"Visual Studio 14 2015 Win32" -DYAML_CPP_BUILD_TOOLS=OFF .
- msbuild /p:Configuration=Release ALL_BUILD.vcxproj
- set CMAKE_LIBRARY_PATH=%CMAKE_LIBRARY_PATH%;%CD%\Release
- set CMAKE_INCLUDE_PATH=%CMAKE_INCLUDE_PATH%;%CD%
- cd ..
# build mongoc
- appveyor DownloadFile https://github.com/mongodb/mongo-c-driver/archive/1.10.2.zip -FileName mongo-c-driver-1.10.2.zip
- 7z x mongo-c-driver-1.10.2.zip
- cd mongo-c-driver-1.10.2
- cmake -G"Visual Studio 14 2015 Win32" -DCMAKE_INSTALL_PREFIX=C:\libraries\mongoc -DENABLE_SSL=OFF -DENABLE_TESTS=OFF
- msbuild /p:Configuration=Release ALL_BUILD.vcxproj
- msbuild /p:Configuration=Release INSTALL.vcxproj
- cd ..
# build mongo-cxx-driver
- git clone --branch releases/stable https://github.com/mongodb/mongo-cxx-driver
- cd mongo-cxx-driver\build
- cmake -G"Visual Studio 14 2015 Win32" -DCMAKE_INSTALL_PREFIX=C:\libraries\mongo-cxx-driver -DCMAKE_PREFIX_PATH=C:\libraries\mongoc -DLIBMONGOC_DIR=C:\libraries\mongoc ..
- msbuild /p:Configuration=Release ALL_BUILD.vcxproj
- msbuild /p:Configuration=Release INSTALL.vcxproj
- cd ..\..\
# build libuv
- git clone -b v1.x https://github.com/libuv/libuv
- cd libuv
- vcbuild release shared x86
- cd ..\..\
- set CMAKE_PREFIX_PATH=%CMAKE_PREFIX_PATH%;C:\libraries\mongo-cxx-driver

build_script:
- cd build
- cmake -G"Visual Studio 14 2015 Win32" -DCMAKE_INSTALL_PREFIX=C:\libraries\mongo-cxx-driver -DCMAKE_PREFIX_PATH=C:\libraries\mongoc;C:\projects\astron\dependencies\libuv;C:\projects\astron\dependencies\libuv\Release -DCMAKE_BUILD_TYPE=Release ..
- msbuild /p:Configuration=Release ALL_BUILD.vcxproj
- cd Release
- copy /Y C:\projects\astron\dependencies\libuv\Release\*.dll .
- copy /Y C:\libraries\mongoc\bin\*.dll .
- copy /Y C:\libraries\mongo-cxx-driver\bin\*.dll .
- 7z a astron.zip *
- cd ..

test_script:
- 7z x Release\astron.zip
- set PATH=%PATH%;C:\mongodb\bin
- ctest --output-on-failure

artifacts:
- path: build\Release\astron.zip
